### ISSUE TITLE
Dots concept

### ISSUE THREAD

**Issue by kylebshr** [joseph346/dots#1]
Dots should not be discriminated against; I believe all dots should be allowed in this language, such as •,  ̇and  ̣ among others. This would also make for a much more interesting language in my opinion. 

This of course depends on the philosophy behind this language; if the goal is to create a language with one character, this clearly isn't a good idea. However, a single-character language doesn't seem too creative or unique, and the name "dots" doesn't make too much sense, as "." could just be replaced with any characters. "dots" is also plural, though I suppose that could refer to the fact that you need multiple dots to write a program. 

I hope you'll consider this proposal, and let me know your thoughts on the matter.

**Comment by jaredthecoder** [comment]
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

**Comment by kylebshr** [comment]
...

**Comment by jaredthecoder** [comment]
....

**Comment by emmaconnor** [comment]
While some programmers may find use in the other various types of dots, I think it is important that we keep the language specification from being too bloated. This way we can ensure that the language is as usable and programmer-friendly as possible!

**Comment by ghost** [comment]
"Programmer-friendly as possible"

I had to spend 3 hours looking through the code just because there was no documentation.
