### ISSUE TITLE
Hello, world...

### ISSUE THREAD

**Issue by yartie** [joseph346/dots#6]
If a massive storage device was created that could hold ~4.2x10^55 yottabytes, would the compiler be able to run the program, or would it take like 10 years to execute?

**Comment by emmaconnor** [comment]
The entire program does not have to fit in main memory, but it does have to be read from disk completely. The load time would depend on the speed of this hypothetical storage.

**Comment by yartie** [comment]
If the storage device was capable of, say, DDR5 RAM, holding such a file would be possible and loading it to the interpreter would be fast enough, right?
